edc:
  env:
    WEB_HTTP_PORT: 8181
    WEB_HTTP_PATH: /api
    WEB_HTTP_IDS_PORT: 8282
    WEB_HTTP_IDS_PATH: /api/v1/ids
    WEB_HTTP_MANAGEMENT_PORT: 9191
    WEB_HTTP_MANAGEMENT_PATH: /api/v1/management
    WEB_HTTP_IDENTITY_PORT: 7171
    WEB_HTTP_IDENTITY_PATH: /api/v1/identity

ports:
  http:
    containerPort: 8181
    servicePort: 80
    path: /api
  ids:
    containerPort: 8282
    servicePort: 8282
    path: /api/v1/ids
  http-mgmt:
    containerPort: 9191
    servicePort: 9191
    path: /api/v1/management
  identity:
    containerPort: 7171
    servicePort: 7171
    path: /api/v1/identity