apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
    {{- include "connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "connector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $k, $v := .Values.ports }}
            - containerPort: {{ $v.containerPort }}
              name: {{ $k }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "connector.fullname" . }}-envvars
            - secretRef:
                name: {{ include "connector.fullname" . }}-envvars
          livenessProbe:
            httpGet:
              path: /api/v1/management/check/liveness
              port: mgmt
              httpHeaders:
                - name: X-Api-Key
                  value: ApiKeyDefaultValue
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/management/check/readiness
              port: mgmt
              httpHeaders:
                - name: X-Api-Key
                  value: ApiKeyDefaultValue
            initialDelaySeconds: 10
          startupProbe:
            httpGet:
              path: /api/v1/management/check/liveness
              port: mgmt
              httpHeaders:
                - name: X-Api-Key
                  value: ApiKeyDefaultValue
            failureThreshold: 60
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.edc.volumeMounts | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
